### PR TITLE
added addChannelBedObjectTo function

### PR DESCRIPTION
**Pull request by benjamin-weiss**
- added ChannelBedObjectHolder struct
- added speakerLabelsLookupTable function
- to align API added addSimpleObjectTo function

### CODE REVIEW

**Comment by benjamin-weiss** [comment]
@firthm01 What do you think about this? Does the API make sense to you?

**Comment by firthm01** [comment]
Yes, it makes sense, but I wonder whether it might be beneficial to move all of the ADM element creation stuff in to a `createChannelBedObject` method (similar to `createSimpleAudioObject`). I think it might be more consistent and would allow people to create a `ChannelBedObjectHolder` without immediately adding it to a document.

**Comment by firthm01** [comment]
It might also be useful to provide access to the `AudioPackFormat`, `AudioChannelFormat`(s), `AudioStreamFormat`(s) and `AudioTrackFormat`(s) within the holder like we do with `SimpleObjectHolder` so the user doesn't need to do reference lookups themselves to do this. e.g,

```
struct ChannelBedObjectHolder {
    std::shared_ptr<AudioObject> audioObject;
    std::shared_ptr<AudioPackFormat> audioPackFormat;
    std::map<std::string, ChannelBedObjectSubElements > subElements;
  };

struct ChannelBedObjectSubElements {
    std::shared_ptr<AudioChannelFormat> audioChannelFormat;
    std::shared_ptr<AudioStreamFormat> audioStreamFormat;
    std::shared_ptr<AudioTrackFormat> audioTrackFormat;
    std::shared_ptr<AudioTrackUid> audioTrackUid;
  };
```
Might be a bit overkill? Although we could then use the same struct regardless of TypeDefinition of the thing being created (but that would break backwards compatibility with any existing implementations expecting a `SimpleObjectHolder`)

**Comment by benjamin-weiss** [comment]
Thanks a lot for the feedback!

Because of how the common definitions work in the libadm it is not possible to write a `createChannelBedObject` function, as we always need an `adm:Document`.

We could add more elements to the `ChannelBedObjectHolder`, but I wonder why one would need easy access to those elements. We already have the `AudioObject` and the `AudioTrackUID`, which provides very easy access to the `AudioTrackFormat` and the `AudioPackFormat`. 

I can thing of two things one might want to do after adding a channel bed.

1. Create the information for the chna chunk
2. Add the channel bed to another `audioObject` or an `audioContent`

Am I missing something one might want to do. And if so is it common enough that it is worth making the `ChannelBedObjectHolder` more complicated?

**Comment by firthm01** [comment]
Ah yes, I guess what I said doesn't really make sense for common definitions since they're already added in to a document on instantiation. I think this solution is fine for common definitions in that case. I presume that some way in the future we may need to provide functions for custom DirectSpeaker configurations, so we just need to be careful with names so that the distinction will be obvious. That being said, perhaps "channel bed" isn't the best term to use, since we don't use it anywhere else and generally only talk about "DirectSpeakers"?

For common definitions it would be overkill to provide a struct like the one I mentioned, since (as you mention) it is only one call in most cases to get each of the referenced elements. I suppose you could argue that is also the case for the elements in `SimpleObjectHolder`, but it makes a bit more sense when they are newly created elements.

**Pull request merged**
